const fs=require('fs'),vm=require('vm'),assert=require('assert');
let states=[],hook=0,effect,first=true,calls=[],changed=0;
const proposal={path:'Factures/Fournisseur Test',root:'NAS',exists:false,expected:{proposed_path:null}};
const context={N:{useState:initial=>{const i=hook++;if(!(i in states))states[i]=initial;return[states[i],v=>states[i]=v]},useEffect:fn=>{if(first)effect=fn}},o:{jsx:(type,props)=>({type,props}),jsxs:(type,props)=>({type,props})},archiveDocumentInfo:()=>({document_type:'invoice'}),archiveMonetary:()=>true,fetch:async(url,opts)=>{calls.push([url,opts]);return{ok:true,json:async()=>opts?{status:'FILED'}:proposal}}};
vm.createContext(context);vm.runInContext(fs.readFileSync('inline_destination.js','utf8'),context);
const doc={id:19,original_filename:'invoice.pdf',legal_entity_id:1,creditor_id:2,invoice_date:'2026-01-20',amount_minor:12345,currency:'CHF',proposed_filename:'Boris.pdf'};
function render(){hook=0;return context.InlineDestination({doc,onChanged:async()=>changed++,simulation:false})}
function nodes(tree,type){if(!tree||typeof tree!=='object')return[];return(tree.type===type?[tree]:[]).concat((Array.isArray(tree.props?.children)?tree.props.children:[tree.props?.children]).flatMap(c=>nodes(c,type)))}
(async()=>{let tree=render();assert(nodes(tree,'button')[0].props.disabled);effect();first=false;await new Promise(setImmediate);tree=render();const input=nodes(tree,'input')[0];assert.equal(input.props.value,'Factures/Fournisseur Test');input.props.onChange({target:{value:'Factures/Fournisseur Test/Prestations'}});tree=render();const button=nodes(tree,'button')[0];assert.equal(button.props.children,'Valider ce dossier et classer');assert(!button.props.disabled);await button.props.onClick();const payload=JSON.parse(calls[1][1].body);assert.equal(payload.path,'Factures/Fournisseur Test/Prestations');assert(payload.confirmed);assert.equal(changed,1);assert.equal(calls[1][0],'/api/v1/documents/19/quick-filing');console.log('Inline queue UI: visible proposal, editing, explicit confirmation and refresh passed.')})().catch(e=>{console.error(e);process.exitCode=1});
