import { useEffect, useState } from 'react';
type State={supported:boolean;running:boolean;status:string;message:string;pages:number;pdf_available:boolean};
type Device={id:string;name:string};
type Props={onImportFile:(file:File)=>Promise<{id:number}>;onOpen:(id:number)=>void;onChanged:()=>void};
export function ScannerPanel({onImportFile,onOpen,onChanged}:Props){
 const [state,setState]=useState<State|null>(null),[devices,setDevices]=useState<Device[]>([]),[selected,setSelected]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(false),[sending,setSending]=useState(false);
 const refreshDevices=async()=>{setLoading(true);setError('');try{const r=await fetch('/api/v1/scanner/devices');if(!r.ok)throw Error('Détection des scanners indisponible.');const data=await r.json();setDevices(data.devices||[]);setMessage(data.message||'');setSelected(previous=>data.devices?.some((d:Device)=>d.id===previous)?previous:data.devices?.[0]?.id||'');}catch(e){setError(String(e))}finally{setLoading(false)}};
 useEffect(()=>{let active=true;const poll=async()=>{try{const r=await fetch('/api/v1/scanner',{cache:'no-store'});if(!r.ok)throw Error('Le scanner est indisponible.');const next=await r.json();if(active)setState(next);}catch(e){if(active)setError(String(e))}};poll();refreshDevices();const timer=window.setInterval(poll,1500);return()=>{active=false;window.clearInterval(timer)}},[]);
 const command=async(action:string)=>{setError('');try{const r=await fetch('/api/v1/scanner',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(action==='scan'?{action,device:selected}:{action})});const next=await r.json();if(!r.ok)throw Error(next.detail||'Numérisation impossible.');setState(next);}catch(e){setError(String(e))}};
 const send=async()=>{setSending(true);setError('');try{const r=await fetch('/api/v1/scanner/pdf',{cache:'no-store'});if(!r.ok)throw Error('Le PDF n’est pas disponible.');const file=new File([await r.blob()],`facture-scan-${new Date().toISOString().slice(0,10)}.pdf`,{type:'application/pdf'});const document=await onImportFile(file);await command('reset');onChanged();onOpen(document.id);}catch(e){setError(String(e))}finally{setSending(false)}};
 return <section className="pilot-pc-inbox"><div className="pilot-page-title"><div><span className="pilot-kicker">NUMÉRISATION</span><h1>Scanner une facture</h1><p>Numérisez, vérifiez le PDF puis lancez son classement.</p></div></div>
 <p>{message||'Scanner USB ou réseau installé dans Windows avec un pilote de numérisation WIA.'}</p>
 {error&&<div className="pilot-alert error" role="alert">{error}</div>}
 <div className="pilot-pc-status"><label htmlFor="scanner-device">Scanner</label><select id="scanner-device" value={selected} disabled={state?.running||sending||loading} onChange={e=>setSelected(e.target.value)}><option value="">{loading?'Recherche des scanners…':'Choisir un scanner'}</option>{devices.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select><button className="pilot-secondary" disabled={loading||state?.running||sending} onClick={refreshDevices}>{loading?'Recherche…':'Actualiser les scanners'}</button></div>
 {!loading&&state?.supported&&!devices.length&&<p>Aucun scanner compatible détecté. Vérifiez la connexion et le pilote WIA du fabricant. Le pilote d’impression seul ne suffit pas.</p>}
 <div className="pilot-pc-status" role="status"><strong>{state?.message||'Chargement…'}</strong>{state?.running&&<progress aria-label="Numérisation en cours"/>}{!!state?.pages&&<span>{state.pages} page(s) dans cette facture</span>}</div>
 <div className="pilot-pc-actions"><button className="pilot-primary" disabled={!state?.supported||!selected||state?.running||sending} onClick={()=>command('scan')}>{state?.running?'Numérisation…':state?.pages?'Ajouter une page':'Numériser la facture'}</button>{state?.pdf_available&&<button className="pilot-primary" disabled={state.running||sending} onClick={send}>{sending?'Envoi au traitement…':'Traiter cette facture'}</button>}{!!state?.pages&&<button className="pilot-secondary" disabled={state.running||sending} onClick={()=>command('reset')}>Nouvelle facture</button>}</div>
 {state?.pdf_available&&!state.running&&<iframe title="Aperçu de la facture numérisée" src={'/api/v1/scanner/pdf?pages='+state.pages} style={{width:'100%',height:'min(70vh,720px)',border:'1px solid #dce8e2',borderRadius:16,marginTop:20}}/>}
 <p><small>La numérisation et la compression en PDF restent locales. L’analyse habituelle commence après « Traiter cette facture ». Ajoutez les pages d’une même facture avant de la traiter. « Nouvelle facture » efface seulement cet aperçu temporaire.</small></p>
 </section>;
}
