async function docPilotFetch(url,options={}){
 const controller=new AbortController(),mutation=options.method&&options.method!=="GET",timer=setTimeout(()=>controller.abort(),mutation?180000:15000);
 try{return await fetch(url,{...options,signal:options.signal||controller.signal})}
 catch(error){
  if(error.name==="AbortError")throw Error(mutation?"Le serveur n’a pas répondu dans le délai prévu. Le traitement peut encore continuer : consultez son état avant de relancer.":"Le serveur ne répond pas. Vérifiez que DocPilot est ouvert, puis actualisez.");
  throw Error("Connexion à DocPilot interrompue. Vérifiez que l’application est ouverte, puis actualisez l’état avant de réessayer.");
 }finally{clearTimeout(timer)}
}
function DocDiagnostics({doc,onChanged}){
 const [info,setInfo]=N.useState(null),[error,setError]=N.useState(""),[saving,setSaving]=N.useState(false);
 N.useEffect(()=>{let live=true,active=false;async function refresh(){if(active)return;active=true;try{const response=await docPilotFetch(`/api/v1/documents/${doc.id}/diagnostics`);if(!response.ok)throw Error("État du document indisponible");const data=await response.json();if(live){setInfo(data);setError("")}}catch(e){if(live)setError(e.message)}finally{active=false}}refresh();const timer=setInterval(refresh,4000);return()=>{live=false;clearInterval(timer)}},[doc.id,doc.status,doc.invoice_date]);
 if(error)return o.jsx("p",{className:"pilot-alert error",role:"alert",children:error});
 if(!info)return null;
 if(info.job)return o.jsxs("div",{className:"pilot-diagnostic",role:"status",children:[o.jsx("strong",{children:info.job.label+" · "+info.job.elapsed_seconds+" s"}),info.job.copy_percent!=null&&o.jsx("small",{children:"Copie vers le dossier de destination : "+info.job.copy_percent+" %"}),info.job.slow&&o.jsx("p",{children:info.job.message})]});
 if(!info.needs_action)return null;
 const dates=(info.dates||[]).filter((entry,index,list)=>list.findIndex(e=>e.date===entry.date&&e.kind===entry.kind)===index);
 async function chooseDate(value){setSaving(true);setError("");try{await F.correct(doc.id,{invoice_date:value});await onChanged()}catch(e){setError(e.message)}finally{setSaving(false)}}
 return o.jsxs("div",{className:"pilot-diagnostic",role:"alert",children:[o.jsx("strong",{children:"Action requise · le traitement est terminé"}),...info.messages.map(message=>o.jsxs("div",{children:[o.jsx("p",{children:message.title}),o.jsx("small",{children:message.action})]},message.code)),!doc.invoice_date&&dates.length>0&&o.jsxs("details",{children:[o.jsx("summary",{children:"Voir les dates lues et confirmer la date d’émission"}),...dates.map(entry=>o.jsxs("div",{className:"pilot-date-choice",children:[o.jsx("span",{children:(entry.label||"Date sans libellé")+" : "+Mc(entry.date)}),o.jsx("small",{children:entry.evidence}),["issue","generic"].includes(entry.kind)&&o.jsx("button",{className:"pilot-secondary",disabled:saving,onClick:()=>chooseDate(entry.date),children:"Confirmer cette date d’émission"})]},entry.kind+entry.date))]})]});
}
function SyncDashboard(){
 const [data,setData]=N.useState(null),[error,setError]=N.useState("");
 N.useEffect(()=>{let live=true,active=false;async function refresh(){if(active)return;active=true;try{const response=await docPilotFetch('/api/v1/sync/status');if(!response.ok)throw Error("Suivi NAS indisponible");const result=await response.json();if(live){setData(result);setError("")}}catch(e){if(live)setError(e.message)}finally{active=false}}refresh();const timer=setInterval(refresh,6000);return()=>{live=false;clearInterval(timer)}},[]);
 return o.jsxs("details",{className:"pilot-sync-dashboard",children:[o.jsx("summary",{children:"Synchronisation NAS · "+(data?.client?.label||"Vérification…")}),error&&o.jsx("p",{className:"pilot-alert error",role:"alert",children:error}),data&&o.jsxs("div",{children:[o.jsx("p",{children:data.client.message}),o.jsx("small",{children:"Le pourcentage de copie dans le dossier et la réception sur le NAS sont deux étapes distinctes. Un pourcentage NAS apparaît uniquement lorsque le fournisseur le confirme."}),!data.files.length&&o.jsx("p",{children:"Aucun fichier classé à synchroniser."}),...data.files.map(file=>o.jsxs("div",{className:"pilot-sync-file",children:[o.jsx("strong",{children:file.filename}),o.jsx("span",{children:file.label}),file.percent!=null&&o.jsx("progress",{value:file.percent,max:100,"aria-label":"Synchronisation de "+file.filename}),o.jsx("small",{children:file.message})]},file.document_id))]})]});
}
function ProcessingStatus(){
 const [seconds,setSeconds]=N.useState(0),[jobs,setJobs]=N.useState([]),[error,setError]=N.useState("");
 N.useEffect(()=>{let live=true,active=false;const started=Date.now();async function refresh(){if(active)return;active=true;try{const response=await docPilotFetch('/api/v1/processing');if(!response.ok)throw Error("État du traitement indisponible");const data=await response.json();if(live){setJobs(data.jobs.filter(job=>job.active));setError("")}}catch(e){if(live)setError(e.message)}finally{active=false}}refresh();const timer=setInterval(()=>{setSeconds(Math.floor((Date.now()-started)/1000));refresh()},2000);return()=>{live=false;clearInterval(timer)}},[]);
 return o.jsxs("div",{className:"pilot-processing-status",role:"status","aria-live":"polite",children:[o.jsx("span",{className:"pilot-processing-spinner","aria-hidden":"true"}),o.jsxs("div",{children:[o.jsx("strong",{children:jobs.length?jobs[0].label:"Demande transmise à DocPilot"}),...jobs.map(job=>o.jsxs("div",{children:[o.jsx("small",{children:(job.filename||"Document "+(job.document_id||"en cours"))+" · "+job.label+" · "+job.elapsed_seconds+" s"}),job.copy_percent!=null&&o.jsx("small",{children:"Copie vers le dossier : "+job.copy_percent+" %"}),job.slow&&o.jsx("p",{children:job.message})]},job.id)),!jobs.length&&o.jsx("small",{children:seconds>=30?"En attente de réponse. Aucun traitement actif n’est confirmé. Consultez l’état du document avant de relancer.":"Préparation ou attente de réponse du serveur."}),error&&o.jsx("p",{className:"pilot-alert error",children:error}),o.jsx("small",{children:"Temps écoulé : "+seconds+" s"})]})]});
}
