const fs=require('fs'),vm=require('vm'),assert=require('assert');
const source=fs.readFileSync(__dirname+'/wine_ui.js','utf8').replace(/export function/g,'function');
const ctx={fetch:()=>{throw Error('Test must not query real API')},N:{useState:x=>[x,()=>{}],useEffect:()=>{}},o:{jsx:(type,props)=>({type,props}),jsxs:(type,props)=>({type,props})}};vm.createContext(ctx);vm.runInContext(source,ctx);
function walk(n,out=[]){if(!n||typeof n!=='object')return out;if(n.type)out.push(n);for(const v of Array.isArray(n.props?.children)?n.props.children:[n.props?.children]){if(Array.isArray(v))v.forEach(x=>walk(x,out));else walk(v,out)}return out}
const docs=[{id:1,status:'FILED',original_filename:'a.pdf',legal_entity_name:'Example',amount_minor:2500,currency:'CHF'},{id:2,status:'ERROR',original_filename:'b.pdf'},{id:3,status:'DUPLICATE',original_filename:'c.pdf'},{id:4,status:'TO_VALIDATE',original_filename:'d.pdf'}];
let go=null,search=null,opened=null;
const shell=ctx.WineShell({page:'home',section:'storage',docs,search:'',onSearch:v=>search=v,navigate:(...a)=>go=a,aiAvailable:true,controls:null,children:'Page'});const nodes=walk(shell);
for(const [label,page,section] of [['Tableau de bord','home'],['Documents','documents'],['Importer un fichier','import'],['Scanner une facture','scanner'],['Rechercher sur ce PC','pc'],['Sociétés','settings','entities'],['Fournisseurs','settings','creditors'],['Intelligence artificielle','settings','ia'],['Classement et application','settings','system'],['Historique','history']]){const item=nodes.find(n=>n.type==='button'&&n.props.children?.some?.(c=>c?.type==='span'&&c.props.children===label));assert(item,label);item.props.onClick();assert.deepEqual(go,[page,section,undefined])}
const notification=nodes.find(n=>n.props.className==='wine-notifications');assert(notification.props['aria-label']==='3 documents à vérifier');notification.props.onClick();assert.deepEqual(go,['documents',undefined,'attention']);
nodes.find(n=>n.props.id==='wine-search').props.onChange({target:{value:'supplier'}});assert.equal(search,'supplier');nodes.find(n=>n.type==='form').props.onSubmit({preventDefault(){}});assert.deepEqual(go,['documents',undefined,'all']);
const dashboard=ctx.WineDashboard({docs,navigate:(...a)=>go=a,onOpen:id=>opened=id});const items=walk(dashboard);const serialized=JSON.stringify(dashboard);assert(serialized.includes('a.pdf')&&serialized.includes('25.00 CHF')&&serialized.includes('Doublon'));assert(!serialized.includes('Connecté'));const first=items.find(n=>n.type==='button'&&Array.isArray(n.props.children)&&n.props.children.some(c=>c?.props?.className==='wine-pdf'));first.props.onClick();assert.equal(opened,1);
const empty=JSON.stringify(ctx.WineDashboard({docs:[],navigate(){},onOpen(){}}));assert(empty.includes('Ajoutez votre première facture'));assert(!empty.includes('ViniWine'));
const bundle=fs.readFileSync(__dirname+'/web/assets/index-CEFd-v_U.js','utf8');assert(bundle.includes('Z==="entities"&&o.jsx(Cp,{}),Z==="creditors"&&o.jsx(Np,{})'));assert(bundle.includes('e==="scanner"&&o.jsx(ScannerPanel'));assert(bundle.includes('e==="pc"&&o.jsx(PcInboxPanel'));assert(bundle.includes('page:e==="import"?"home":e'));assert(bundle.includes('o.jsx(WorkspaceGate,{})'));assert(bundle.includes('Doublons et synchronisation'));assert(bundle.includes('o.jsx(ArchiveScanControl,{onChanged})'));
const css=fs.readFileSync(__dirname+'/web/assets/index-WlkB-kjt.css','utf8');assert(css.includes("url('/wine-hero.png')"));assert(!css.includes('wine-landscape.svg'));assert(css.includes(':root[data-theme=dark] .wine-mark'));assert(css.includes('.wine-layout .pilot-audit-meta b'));
console.log('PASS: complete sidebar navigation, correct company/supplier mapping, actual attention badges, search submission, invoice opening, empty state, retained filing/scanner/PC controls and burgundy dark theme.');
